// <auto-generated />
using BrickOutService.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrickOutService.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrickOutService.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Nokia"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Lenova"
                        });
                });

            modelBuilder.Entity("BrickOutService.Models.TypeOfDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypesOfDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Game console"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Watch"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
